name: "Python Test Action"
description: "Python Test Action."
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  url:
    description: "URL with {ref} in String"
    required: true

outputs:
  url:
    description: "URL Output"

runs:
  using: "docker"
  image: "Dockerfile"
